import type { Metadata } from "next";
import { Inter  } from "next/font/google"
import Header from "@/components/Header";
import SideBar from "@/components/SideBar";
import { Toaster } from "@/components/ui/toaster";
import { getServerSession } from "next-auth";
import { authOptions } from "../api/auth/[...nextauth]/route";
import { UserJson } from "@/interface";
import GetUserProfile from "@/lib/GetUserProfile";
import { redirect } from "next/navigation";
import { useToast } from "@/components/ui/use-toast";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <>
      <Header />
      <SideBar >
        {children}
      </SideBar>
    </>
  );
}
