import type { Metadata } from "next";
import { Inter  } from "next/font/google"
import Header from "@/components/Header";
import SideBar from "@/components/SideBar";
import { Toaster } from "@/components/ui/toaster";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body className={inter.className}>
          <Header />
          <SideBar >
            {children}
            <Toaster/>
          </SideBar>
      </body>
    </html>
  );
}
